# Generated by Django 4.2.7 on 2025-05-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('preferred_foot', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], default='right', max_length=5)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('appearances', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('expected_goals', models.FloatField(default=0.0)),
                ('expected_assists', models.FloatField(default=0.0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('pass_completion', models.FloatField(default=0.0)),
                ('tackles', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('fbref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.position')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
            options={
                'ordering': ['team', 'last_name', 'first_name'],
            },
        ),
    ]
