# Generated by Django 4.2.7 on 2025-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pass_completion',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
