version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=futballiq_user
      - POSTGRES_PASSWORD=futballiq_password
      - POSTGRES_DB=futballiq_dev

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: 